
app_realizar_orden:
    path: /realizar_orden
    defaults: { _controller: AppBundle:Pedidos:realizar_orden }

app_obtener_pedidos:
    path: /obtener_pedidos
    defaults: { _controller: AppBundle:Pedidos:obtener_pedidos }

