

app_obtener_productos:
    path: /obtener_productos_page
    defaults: { _controller: AppBundle:Productos:obtener_productos }

app_productos_Categoria:
    path: /categoria/{linea}/{pagina}
    defaults: { _controller: AppBundle:Productos:productosPorTipo }
