AppBundle\Entity\Lineas:
    repositoryClass: AppBundle\Entity\LineasRepository
    type: entity
    table: lineas
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        linea:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        icono:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
    lifecycleCallbacks: {  }
