AppBundle\Entity\Login:
    repositoryClass: AppBundle\Entity\LoginRepository
    type: entity
    table: login
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        correo:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        contrasena:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        token:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
    lifecycleCallbacks: {  }
