AppBundle\Entity\OrdenesDetalle:
    repositoryClass: AppBundle\Entity\OrdenesDetalleRepository
    type: entity
    table: ordenes_detalle
    indexes:
        ordenenFK:
            columns:
                - orden_id
        OD_produto_Key:
            columns:
                - producto_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        producto:
            targetEntity: Productos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                producto_id:
                    referencedColumnName: codigo
            orphanRemoval: false
        orden:
            targetEntity: Ordenes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                orden_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
