AppBundle\Entity\OrdenesDetalle:
    repositoryClass: AppBundle\Entity\OrdenesDetalleRepository
    type: entity
    table: ordenes_detalle
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ordenId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: orden_id
        productoId:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            column: producto_id
    lifecycleCallbacks: {  }
