AppBundle\Entity\Ordenes:
    repositoryClass: AppBundle\Entity\OrdenesRepository
    type: entity
    table: ordenes
    indexes:
        ordenes_usuarioFK:
            columns:
                - usuario_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        creadoEn:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: creado_en
    manyToOne:
        usuario:
            targetEntity: Login
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
