AppBundle\Entity\Productos:
    repositoryClass: AppBundle\Entity\ProductosRepository
    type: entity
    table: productos
    indexes:
        lineaFK:
            columns:
                - linea_id
    id:
        codigo:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        producto:
            type: string
            nullable: false
            length: 70
            options:
                fixed: false
        linea:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        proveedor:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        descripcion:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        precioCompra:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            column: precio_compra
    manyToOne:
        linea2:
            targetEntity: Lineas
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                linea_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
