<?php

namespace AppBundle\Entity;

/**
 * LineasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineasRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLineas() {
        $em = $this->getEntityManager();
        $dql = 'Select l
                from AppBundle:Lineas l
               ';
        $query = $em->createQuery($dql);
        $lineas= $query->getArrayResult();
        return $lineas;
    }
}
