<?php

namespace AppBundle\Entity;

/**
 * OrdenesDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenesDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
