<?php

namespace AppBundle\Entity;

/**
 * OrdenesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenesRepository extends \Doctrine\ORM\EntityRepository
{
}
