<?php

namespace AppBundle\Entity;

/**
 * ProductosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductosRepository extends \Doctrine\ORM\EntityRepository
{
   public function getProductosPage($pagina){
     $em = $this->getEntityManager();
     $dql = 'Select p
             from AppBundle:Productos p
            ';
     $query = $em->createQuery($dql)
              ->setFirstResult($pagina)
              ->setMaxResults(10);

     $productos= $query->getArrayResult();
     return $productos;
   }


}
