<?php

namespace AppBundle\Entity;

/**
 * ProductosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductosRepository extends \Doctrine\ORM\EntityRepository
{
    public function verProducto($codigo) {
        $em = $this->getEntityManager();
        $dql = 'Select p, g
                from BDBundle:Producto p
                join p.gama g
                where p.codigoproducto = :codigo
                
               ';
        $query = $em->createQuery($dql)
                    ->setParameter('codigo', $codigo);
        $producto = $query->getSingleResult();
        return $producto;
    }
    
    public function getProductos() {
        $em = $this->getEntityManager();
        $dql = 'Select p
                from BDBundle:Producto p
               ';
        $query = $em->createQuery($dql);
        $productos= $query->getArrayResult();
        return $productos;
    }
    public function getProductosGama($gama) {
        $em = $this->getEntityManager();
        $dql = 'Select p
                from BDBundle:Producto p
                join p.gama g
                where g.gama = :gama
               ';
        $query = $em->createQuery($dql)
                ->setParameter('gama', $gama);
        //$productos= $query->getArrayResult();
        return $query;
    }
}
